- name: C/CPP
  logo: c%2B%2B
  url: https://www.cplusplus.com/
  color: 00599C
  projects:
    - url: https://github.com/sweatpotato13/Sigpatch-Updater
    - url: https://github.com/sweatpotato13/ELER

- name: CSharp
  logo: c%23
  url: https://docs.microsoft.com/ko-kr/dotnet/csharp/
  color: 23911F
  projects:
    - url: https://github.com/sweatpotato13/Unity-Shooting-Game

- name: Unity
  logo: unity
  url: https://unity.com/
  color: 0A0A0A
  projects:
    - url: https://github.com/sweatpotato13/Unity-Shooting-Game

- name: NestJS
  logo: nestjs
  url: https://nestjs.com/
  color: E0234E
  projects:
    - url: https://github.com/sweatpotato13/nestjs-boilerplate
    - url: https://github.com/sweatpotato13/PSrating-discord-bot
    - url: https://github.com/sweatpotato13/github-profile-psbadge
    - url: https://github.com/sweatpotato13/AtCoderUserInfoAPI
    - url: https://github.com/sweatpotato13/AtCoderUserInfoDB

- name: Swift
  logo: swift
  url: https://swift.org/
  color: E45530
  projects:
    - url: https://github.com/sweatpotato13/CurrencyConverter
    - url: https://github.com/sweatpotato13/Sudoku
    - url: https://github.com/sweatpotato13/dodoList

- name: JavaScript
  logo: javascript
  url: https://www.javascript.com/
  color: F1E05A
  projects:
    - url: https://github.com/sweatpotato13/WhereWeMeet

- name: Typescript
  logo: typescript
  url: https://www.typescriptlang.org/
  color: 3178C6
  projects:
    - url: https://github.com/sweatpotato13/nestjs-boilerplate
    - url: https://github.com/sweatpotato13/nodejs-typescript-boilerplate
    - url: https://github.com/sweatpotato13/react-typescript-boilerplate
    - url: https://github.com/sweatpotato13/react-native-boilerplate
    - url: https://github.com/sweatpotato13/PSrating-discord-bot
    - url: https://github.com/sweatpotato13/github-profile-psbadge
    - url: https://github.com/sweatpotato13/AtCoderUserInfoDB
    - url: https://github.com/sweatpotato13/AtCoderUserInfoAPI
    - url: https://github.com/sweatpotato13/devPlayAutoCoupon
    - url: https://github.com/sweatpotato13/etherscan-ts
    - url: https://github.com/sweatpotato13/lizard-ts
    - url: https://github.com/sweatpotato13/cutewisp

- name: React-Native
  logo: react
  url: https://reactnative.dev/
  color: 61DAFB
  projects:
    - url: https://github.com/sweatpotato13/react-native-boilerplate
    - url: https://github.com/sweatpotato13/WhereWeMeet

- name: React
  logo: react
  url: https://ko.reactjs.org/
  color: 61DAFB
  projects:
    - url: https://github.com/sweatpotato13/react-typescript-boilerplate
    - url: https://github.com/sweatpotato13/cutewisp

- name: Docker
  logo: docker
  url: https://www.docker.com/
  color: 4FA1EF
  projects:
    - url: https://github.com/sweatpotato13/github-profile-psbadge
    - url: https://github.com/sweatpotato13/AtCoderUserInfoDB
    - url: https://github.com/sweatpotato13/AtCoderUserInfoAPI
    
- name: NPM
  logo: npm
  url: https://www.npmjs.com/
  color: CB3837
  projects:
    - url: https://github.com/sweatpotato13/devPlayAutoCoupon
    - url: https://github.com/sweatpotato13/etherscan-ts
    - url: https://github.com/sweatpotato13/lizard-ts
