- name: C/CPP
  logo: c%2B%2B
  url: https://www.cplusplus.com/
  color: 00599C
  projects:
    - https://github.com/sweatpotato13/Sigpatch-Updater
    - https://github.com/sweatpotato13/ELER

- name: CSharp
  logo: c%23
  url: https://docs.microsoft.com/ko-kr/dotnet/csharp/
  color: 23911F
  projects:
    - https://github.com/sweatpotato13/Unity-Project

- name: Unity
  logo: unity
  url: https://unity.com/
  color: 0A0A0A
  projects:
    - https://github.com/sweatpotato13/Unity-Project

- name: NestJS
  logo: nestjs
  url: https://nestjs.com/
  color: E0234E
  projects:
    - https://github.com/sweatpotato13/nestjs-boilerplate
    - https://github.com/sweatpotato13/PSrating-discord-bot
    - https://github.com/sweatpotato13/github-profile-psbadge

- name: Swift
  logo: swift
  url: https://swift.org/
  color: E45530
  projects:
    - https://github.com/sweatpotato13/CurrencyConverter
    - https://github.com/sweatpotato13/Sudoku
    - https://github.com/sweatpotato13/dodoList

- name: JavaScript
  logo: javascript
  url: https://www.javascript.com/
  color: F1E05A
  projects:
    - https://github.com/sweatpotato13/WhereWeMeet

- name: Typescript
  logo: typescript
  url: https://www.typescriptlang.org/
  color: 3178C6
  projects:
    - https://github.com/sweatpotato13/nestjs-boilerplate
    - https://github.com/sweatpotato13/nodejs-typescript-boilerplate
    - https://github.com/sweatpotato13/PSrating-discord-bot
    - https://github.com/sweatpotato13/github-profile-psbadge

- name: React-Native
  logo: react
  url: https://www.javascript.com/
  color: 61DAFB
  projects:
    - https://github.com/sweatpotato13/WhereWeMeet

- name: Docker
  logo: docker
  url: https://www.docker.com/
  color: 4FA1EF
  projects:
    - https://github.com/sweatpotato13/github-profile-psbadge
