name: Profile Stack

on:
  push:
    branches:
      - main
      - test/stack

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Matt-Gleich/profile_stack@master
